package com.micro.pojo;

import java.util.Date;

public class HouseInfo {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column house.house_id
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	private Long houseId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column house.user_id
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	private Long userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column house.house_name
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	private String houseName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column house.house_address
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	private String houseAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column house.house_price
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	private Long housePrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column house.house_area
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	private Integer houseArea;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column house.is_sold
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	private Integer isSold;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column house.is_deleted
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	private Integer isDeleted;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column house.create_time
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column house.own_user
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	private Long ownUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column house.status
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	private Integer status;

	private String ownerName;

	public String getOwnerName() {
		return ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column house.house_id
	 *
	 * @return the value of house.house_id
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public Long getHouseId() {
		return houseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column house.house_id
	 *
	 * @param houseId
	 *            the value for house.house_id
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public void setHouseId(Long houseId) {
		this.houseId = houseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column house.user_id
	 *
	 * @return the value of house.user_id
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column house.user_id
	 *
	 * @param userId
	 *            the value for house.user_id
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column house.house_name
	 *
	 * @return the value of house.house_name
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public String getHouseName() {
		return houseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column house.house_name
	 *
	 * @param houseName
	 *            the value for house.house_name
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public void setHouseName(String houseName) {
		this.houseName = houseName == null ? null : houseName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column house.house_address
	 *
	 * @return the value of house.house_address
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public String getHouseAddress() {
		return houseAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column house.house_address
	 *
	 * @param houseAddress
	 *            the value for house.house_address
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public void setHouseAddress(String houseAddress) {
		this.houseAddress = houseAddress == null ? null : houseAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column house.house_price
	 *
	 * @return the value of house.house_price
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public Long getHousePrice() {
		return housePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column house.house_price
	 *
	 * @param housePrice
	 *            the value for house.house_price
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public void setHousePrice(Long housePrice) {
		this.housePrice = housePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column house.house_area
	 *
	 * @return the value of house.house_area
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public Integer getHouseArea() {
		return houseArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column house.house_area
	 *
	 * @param houseArea
	 *            the value for house.house_area
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public void setHouseArea(Integer houseArea) {
		this.houseArea = houseArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column house.is_sold
	 *
	 * @return the value of house.is_sold
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public Integer getIsSold() {
		return isSold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column house.is_sold
	 *
	 * @param isSold
	 *            the value for house.is_sold
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public void setIsSold(Integer isSold) {
		this.isSold = isSold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column house.is_deleted
	 *
	 * @return the value of house.is_deleted
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public Integer getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column house.is_deleted
	 *
	 * @param isDeleted
	 *            the value for house.is_deleted
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column house.create_time
	 *
	 * @return the value of house.create_time
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column house.create_time
	 *
	 * @param createTime
	 *            the value for house.create_time
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column house.own_user
	 *
	 * @return the value of house.own_user
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public Long getOwnUser() {
		return ownUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column house.own_user
	 *
	 * @param ownUser
	 *            the value for house.own_user
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public void setOwnUser(Long ownUser) {
		this.ownUser = ownUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column house.status
	 *
	 * @return the value of house.status
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column house.status
	 *
	 * @param status
	 *            the value for house.status
	 *
	 * @mbggenerated Fri Apr 22 16:55:58 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}
